### ISSUE TITLE
java.lang.IllegalStateException StartNewChatActivity You need to use a Theme.AppCompat theme 

### ISSUE THREAD

**Issue by ahmedsalamay** [Teknasyon-Teknoloji/desk360-livechat-android-sdk#11]
```
Flutter SDK: 3.0.5
compileSdkVersion 33
minSdkVersion 21
targetSdkVersion 33
classpath 'com.android.tools.build:gradle:7.2.1'
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
implementation 'com.github.Teknasyon-Teknoloji:desk360-livechat-android-sdk:1.2.3'
dataBinding: true
```

I am getting this error while trying to do a simple test just like the example inside the docs

```
   val liveChatManager = LiveChatManager.Builder()
            .setDomainAddress("https://8orders.desk360.com")
            .setToken("token")
            .setLanguageCode("tr")
            .setUserName("Luke")
            .setUserEmailAddress("luke@emailadress.com")
            .setSmartPlug(settings)
            .build()
```

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.test/com.desk360.livechat.presentation.activity.livechat.StartNewChatActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7562)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Comment by ahmedsalamay** [comment]
The issue has been resolved by adding android:theme="@style/Theme.AppCompat.Light" inside application tag
